[package]
name = "shared"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
# Serialization
# No dependencies needed for now

# MoonZoon shared utilities
zoon = { workspace = true }