[package]
name = "frontend"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
zoon.workspace = true
fast2d = { path = "../../crates/fast2d", features = ["webgpu"], default-features = false }
