[config]
default_to_workspace = false
min_version = "0.35.13"
unstable_features = ["CTRL_C_HANDLING"]
skip_core_tasks = true

[config.modify_core_tasks]
private = true
namespace = "default"

#######  MAIN TASKS  #######

[tasks.install]
description = "Install all dependencies. It's NoOp if all deps are already installed."
dependencies = [
    "install_wasm_target", 
    "install_mzoon", 
    "install_cef_deps",
]

[tasks.cef]
description = "Run CEF application"
command = "cargo"
args = ["run", "--manifest-path", "src-cef/Cargo.toml", "${@}"]

[tasks.cef_build]
description = "Build CEF application for release"
command = "cargo"
args = ["build", "--release", "--manifest-path", "src-cef/Cargo.toml"]

[tasks.cef_dev]
description = "Start CEF app (expects MoonZoon server running separately)"
command = "cargo"
args = ["run", "--manifest-path", "src-cef/Cargo.toml"]

[tasks.mzoon]
description = "Run MZoon"
command = "mzoon/bin/mzoon"
args = ["${@}"]

# [tasks.mzoon]
# description = "Run MZoon"
# command = "cargo"
# args = ["run", "--manifest-path", "../../MoonZoon/crates/mzoon/Cargo.toml", "${@}"]

######  HELPER TASKS  ######

[tasks.install_wasm_target]
description = "Install Rust target `wasm32-unknown-unknown`"
command = "rustup"
args = ["target", "add", "wasm32-unknown-unknown"]

[tasks.install_cef_deps]
description = "Install CEF dependencies for Linux"
condition = { platforms = ["linux"] }
script = [
    "echo 'Installing CEF dependencies for Linux...'",
    "sudo apt update || true",
    "sudo apt install -y libx11-dev libxcomposite-dev libxcursor-dev libxdamage-dev libxext-dev libxfixes-dev libxi-dev libxrandr-dev libxrender-dev libxss-dev libxtst-dev libgtk-3-dev libgdk-pixbuf2.0-dev || echo 'Some packages may already be installed'",
    "echo '✅ CEF dependencies installed'",
]

[tasks.install_mzoon]
description = "Install MoonZoon CLI (mzoon) locally"
command = "cargo"
args = [
    "install", 
    "mzoon", 
    "--git", 
    "https://github.com/MoonZoon/MoonZoon",
    "--locked",
    "--rev",
    "507832338c442ee5e7d19b1aa4fc49d7034d5ed0",
    "--root",
    "mzoon",
]
